# Generated by Django 4.0.4 on 2022-08-28 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.IntegerField()),
                ('username', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=100)),
                ('datetime', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
