# Generated by Django 4.1 on 2023-04-13 12:43

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("user_id", models.IntegerField(verbose_name="ID")),
                (
                    "username",
                    models.CharField(
                        db_collation="utf8mb4_0900_as_cs",
                        default=None,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="帳照",
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        db_collation="utf8mb4_0900_as_cs",
                        default="xxxxx@.com",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        db_collation="utf8mb4_0900_as_cs",
                        default=None,
                        max_length=100,
                        verbose_name="密碼",
                    ),
                ),
                (
                    "datetime",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="創建日期"
                    ),
                ),
                ("permissions", models.BooleanField(default=False, verbose_name="權限")),
                (
                    "last_login",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="上次登入日期"
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶管理",
                "verbose_name_plural": "用戶管理",
                "db_table": "member",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Popular_job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "popular_job_user",
                    models.ForeignKey(
                        db_column="popular_job_user",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysql_member.member",
                        verbose_name="使用者",
                    ),
                ),
                (
                    "popular_jobid",
                    models.ForeignKey(
                        db_column="popular_jobid",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.getjob",
                        verbose_name="工作id",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作歡迎度",
                "verbose_name_plural": "工作歡迎度",
                "db_table": "Popular_job",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
