# Generated by Django 4.1 on 2023-05-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysql_member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="user_id",
            field=models.IntegerField(unique=True, verbose_name="ID"),
        ),
    ]
