# Generated by Django 4.1 on 2023-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysql_member", "0002_alter_member_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="line_user_id",
            field=models.CharField(
                db_collation="utf8mb4_0900_as_cs",
                max_length=200,
                null=True,
                unique=True,
                verbose_name="line_id",
            ),
        ),
    ]
