# Generated by Django 4.1 on 2023-06-03 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysql_member", "0003_member_line_user_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="line_user_id",),
    ]
