# Generated by Django 4.1 on 2023-04-13 12:43

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job_type",
            fields=[
                ("job_id", models.IntegerField(unique=True, verbose_name="id")),
                (
                    "type_name",
                    models.CharField(
                        max_length=300,
                        primary_key=True,
                        serialize=False,
                        verbose_name="類名稱",
                    ),
                ),
                (
                    "type_url_1111",
                    models.CharField(
                        default="null", max_length=2000, verbose_name="url_1111"
                    ),
                ),
                (
                    "type_url_104",
                    models.CharField(
                        default="null", max_length=2000, verbose_name="url_104"
                    ),
                ),
            ],
            options={
                "verbose_name": "工作類別",
                "verbose_name_plural": "工作類別",
                "db_table": "job_type",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="total_type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_type_name",
                    models.CharField(max_length=300, unique=True, verbose_name="總類別表"),
                ),
            ],
            options={
                "verbose_name": "總類別表",
                "verbose_name_plural": "總類別表",
                "db_table": "total_type",
            },
        ),
        migrations.CreateModel(
            name="trend",
            fields=[
                (
                    "trend_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("trend_skill", models.CharField(max_length=230, verbose_name="趨勢技能")),
                ("trend_count", models.IntegerField(verbose_name="次數")),
                (
                    "trend_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                (
                    "trend_type",
                    models.ForeignKey(
                        db_column="trend_type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.job_type",
                        verbose_name="技能工作類型",
                    ),
                ),
            ],
            options={
                "verbose_name": "趨勢分析",
                "verbose_name_plural": "趨勢分析",
                "db_table": "trend",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Popular_searches",
            fields=[
                (
                    "Popular_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "Popular_skill",
                    models.CharField(max_length=300, verbose_name="skill"),
                ),
                ("Popular_count", models.IntegerField(verbose_name="次數")),
                (
                    "Popular_type",
                    models.ForeignKey(
                        db_column="popular_type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.job_type",
                        verbose_name="工作類",
                    ),
                ),
            ],
            options={"db_table": "Popular_searches",},
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="job_type",
            name="total_type_name",
            field=models.ForeignKey(
                db_column="total_type_name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myApp.total_type",
                verbose_name="總類名稱",
            ),
        ),
        migrations.CreateModel(
            name="getjob",
            fields=[
                ("jobid", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default="無", verbose_name="發布日期")),
                (
                    "get_website_id",
                    models.CharField(
                        default="", max_length=300, unique=True, verbose_name="工作編號"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("local", models.CharField(max_length=300, verbose_name="工作地點")),
                ("content", models.CharField(max_length=5000, verbose_name="工作內容")),
                ("salary", models.CharField(max_length=150, verbose_name="薪資")),
                ("company", models.CharField(max_length=600, verbose_name="公司")),
                ("href", models.CharField(max_length=100, verbose_name="工作連結")),
                (
                    "experience",
                    models.CharField(default=None, max_length=200, verbose_name="經驗要求"),
                ),
                (
                    "Education",
                    models.CharField(default=None, max_length=200, verbose_name="學歷限制"),
                ),
                (
                    "department",
                    models.CharField(default=None, max_length=200, verbose_name="部門"),
                ),
                (
                    "skill",
                    models.CharField(default=None, max_length=600, verbose_name="所需技能"),
                ),
                (
                    "language",
                    models.CharField(default=None, max_length=600, verbose_name="語言限制"),
                ),
                (
                    "Additional_conditions",
                    models.CharField(
                        default=None, max_length=3000, verbose_name="附加條件"
                    ),
                ),
                (
                    "other",
                    models.CharField(default=None, max_length=3000, verbose_name="其他"),
                ),
                (
                    "website",
                    models.CharField(default=None, max_length=45, verbose_name="網站來源"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        db_column="type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.job_type",
                        verbose_name="工作類型",
                    ),
                ),
            ],
            options={
                "verbose_name": "職缺管理",
                "verbose_name_plural": "職缺管理",
                "db_table": "job_table",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="crawler",
            fields=[
                (
                    "crawler_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "crawler_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                (
                    "crawler_website",
                    models.CharField(max_length=200, verbose_name="爬取網站"),
                ),
                ("crawler_count", models.CharField(max_length=300, verbose_name="數量")),
                ("crawler_state", models.BooleanField(default=True, verbose_name="狀態")),
                (
                    "crawler_contents",
                    models.CharField(max_length=2300, null=True, verbose_name="詳細內容"),
                ),
                (
                    "crawler_type",
                    models.ForeignKey(
                        db_column="crawler_type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.job_type",
                        verbose_name="爬取工作類型",
                    ),
                ),
            ],
            options={
                "verbose_name": "爬蟲日誌",
                "verbose_name_plural": "爬蟲日誌",
                "db_table": "crawler_log",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="popular_searches",
            constraint=models.UniqueConstraint(
                fields=("Popular_skill", "Popular_type"),
                name="Popular_skill_type_unique",
            ),
        ),
    ]
