# Generated by Django 4.0.4 on 2022-08-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getjob',
            fields=[
                ('id', models.IntegerField()),
                ('date', models.DateField(default='無')),
                ('title', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=5000)),
                ('salary', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=600)),
                ('href', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('experience', models.CharField(default=None, max_length=200)),
                ('Education', models.CharField(default=None, max_length=200)),
                ('department', models.CharField(default=None, max_length=200)),
                ('skill', models.CharField(default=None, max_length=600)),
                ('language', models.CharField(default=None, max_length=600)),
                ('Additional_conditions', models.CharField(default=None, max_length=3000)),
                ('other', models.CharField(default=None, max_length=3000)),
                ('website', models.CharField(default=None, max_length=45)),
            ],
            options={
                'db_table': 'software_engineer',
            },
        ),
        migrations.CreateModel(
            name='getjob_firmware',
            fields=[
                ('id', models.IntegerField()),
                ('date', models.DateField(default='無')),
                ('title', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=5000)),
                ('salary', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=600)),
                ('href', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('experience', models.CharField(default=None, max_length=200)),
                ('Education', models.CharField(default=None, max_length=200)),
                ('department', models.CharField(default=None, max_length=200)),
                ('skill', models.CharField(default=None, max_length=600)),
                ('language', models.CharField(default=None, max_length=600)),
                ('Additional_conditions', models.CharField(default=None, max_length=3000)),
                ('other', models.CharField(default=None, max_length=3000)),
                ('website', models.CharField(default=None, max_length=45)),
            ],
            options={
                'db_table': 'Firmware_Engineer',
            },
        ),
        migrations.CreateModel(
            name='getjob_hardware',
            fields=[
                ('id', models.IntegerField()),
                ('date', models.DateField(default='無')),
                ('title', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=5000)),
                ('salary', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=600)),
                ('href', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('experience', models.CharField(default=None, max_length=200)),
                ('Education', models.CharField(default=None, max_length=200)),
                ('department', models.CharField(default=None, max_length=200)),
                ('skill', models.CharField(default=None, max_length=600)),
                ('language', models.CharField(default=None, max_length=600)),
                ('Additional_conditions', models.CharField(default=None, max_length=3000)),
                ('other', models.CharField(default=None, max_length=3000)),
                ('website', models.CharField(default=None, max_length=45)),
            ],
            options={
                'db_table': 'hardware_engineer',
            },
        ),
    ]
