# Generated by Django 4.0.4 on 2022-05-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
