# Generated by Django 4.1 on 2023-05-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawler",
            name="crawler_total_count",
            field=models.IntegerField(default=0, verbose_name="爬取總數"),
        ),
    ]
