# Generated by Django 4.0.4 on 2022-05-28 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_userinfo_pwd_userinfo_stock_userinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='datatime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
