# Generated by Django 4.1 on 2023-07-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_crawler_crawler_total_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="getjob",
            name="certificate",
            field=models.CharField(default="不拘", max_length=700),
        ),
    ]
