# Generated by Django 4.1 on 2023-07-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_getjob_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="getjob",
            name="salary_int",
            field=models.IntegerField(default=0, verbose_name="薪水值"),
        ),
    ]
