# Generated by Django 4.1 on 2023-04-13 12:43

import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myApp", "0001_initial"),
        ("mysql_member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "Notice_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "Notice_content",
                    models.CharField(max_length=3000, verbose_name="通知內容"),
                ),
                (
                    "Notice_title",
                    models.CharField(
                        default="推送通知", max_length=300, verbose_name="通知標題"
                    ),
                ),
                (
                    "Notice_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="通知日期"
                    ),
                ),
                ("Notice_look", models.BooleanField(verbose_name="是否查看")),
                (
                    "Notice_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysql_member.member",
                        verbose_name="通知帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知中心",
                "verbose_name_plural": "通知中心",
                "db_table": "Notic",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Recommend_log",
            fields=[
                (
                    "relog_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "relog_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="推送時間"
                    ),
                ),
                ("relog_count", models.IntegerField(verbose_name="推送數量")),
                ("relog_state", models.BooleanField(default=True, verbose_name="狀態")),
                (
                    "relog_content",
                    models.CharField(max_length=3000, null=True, verbose_name="詳細內容"),
                ),
                (
                    "relog_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysql_member.member",
                        verbose_name="推送帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "推送日誌",
                "verbose_name_plural": "推送日誌",
                "db_table": "Recommend_log",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Recommend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recom_open",
                    models.BooleanField(default=False, verbose_name="是否開啟推送"),
                ),
                (
                    "recom_skill",
                    models.CharField(default="", max_length=300, verbose_name="推送篩選技能"),
                ),
                (
                    "recom_fraction",
                    models.CharField(max_length=300, null=True, verbose_name="推送篩選標準"),
                ),
                (
                    "recom_count",
                    models.CharField(default="0", max_length=300, verbose_name="推送數量"),
                ),
                ("recom_local", models.CharField(max_length=300, null=True)),
                (
                    "recom_email_open",
                    models.BooleanField(default=False, verbose_name="是否開啟Email推送"),
                ),
                (
                    "recom_job_type",
                    models.ForeignKey(
                        db_column="recom_job_type",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myApp.job_type",
                        verbose_name="推送工作類型",
                    ),
                ),
                (
                    "recom_user_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysql_member.member",
                        verbose_name="帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "推送管理",
                "verbose_name_plural": "推送管理",
                "db_table": "Recommend",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "opinion_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "opinion_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="時間"
                    ),
                ),
                ("opinion_type", models.CharField(max_length=300, verbose_name="意見類型")),
                (
                    "opinion_content",
                    models.CharField(max_length=5000, verbose_name="意見內容"),
                ),
                (
                    "opinion_img",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "opinion_response",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.notice",
                        verbose_name="回覆狀態",
                    ),
                ),
                (
                    "opinion_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysql_member.member",
                        verbose_name="帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "意見箱",
                "verbose_name_plural": "意見箱",
                "db_table": "Opinion",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "like_user_skill",
                    models.CharField(default="", max_length=200, verbose_name="用戶技能"),
                ),
                (
                    "like_type",
                    models.CharField(
                        default="like", max_length=200, verbose_name="工作類型"
                    ),
                ),
                (
                    "like_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        max_length=300,
                        verbose_name="添加時間",
                    ),
                ),
                (
                    "like_jobid",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_id",
                        to="myApp.getjob",
                        verbose_name="工作id",
                    ),
                ),
                (
                    "like_user_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_name",
                        to="mysql_member.member",
                        verbose_name="帳號",
                    ),
                ),
            ],
            options={
                "verbose_name": "用戶最愛管理",
                "verbose_name_plural": "用戶最愛管理",
                "db_table": "Like",
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
