# Generated by Django 4.1 on 2023-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommend",
            name="recom_line_bot",
            field=models.BooleanField(default=False, verbose_name="是否開啟line-bot推送"),
        ),
    ]
