# Generated by Django 4.1 on 2023-08-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_recommend_recom_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="like_certificate",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
