# Generated by Django 4.1 on 2023-08-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_like_like_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommend",
            name="recom_cer_boo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recommend",
            name="recom_cer_fraction",
            field=models.CharField(
                default="max", max_length=300, null=True, verbose_name="推送篩選標準"
            ),
        ),
        migrations.AddField(
            model_name="recommend",
            name="recom_certificate",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
